### ISSUE TITLE
Demand access to wastewater plant. Deadline: 28/11/16.

### ISSUE THREAD

**Issue by aliceleydier** [aliceleydier/AutotrophicReactor#7]

**Comment by Maurorodar** [comment]
Waiting for Janeth's singnature 

https://drive.google.com/open?id=0B_M8fnSCuk-aSlJFMVpjM081Sms

**Comment by aliceleydier** [comment]
Mauricio need to write the letter

**Comment by Maurorodar** [comment]
Done. Waiting for the answer of the company
